<#
make-shareable.ps1 — one-shot: build afterterm and pack it into a single
~67 MB self-extracting afterterm-setup.exe to hand to another machine.

RUN THIS FROM A NORMAL TERMINAL (Windows Terminal / PowerShell), NOT from
inside afterterm. The build overwrites out\afterterm-win32-x64\, which is
locked while afterterm is running from it — so close all afterterm windows
first. (See docs/guide-01-distributable-build.md for the why.)

Usage:
    cd D:\Tinkering\afterterm
    pwsh -File scripts\make-shareable.ps1            # strips non-English locales (smallest, ~67 MB)
    pwsh -File scripts\make-shareable.ps1 -KeepLocales   # safe for non-English Windows (~larger)

TLS: this script runs the build with Node's --use-system-ca so it trusts the
Windows certificate store — that fixes the "unable to verify the first
certificate" error on machines behind an intercepting proxy / corporate root CA
(the secure way, using your real installed CAs). If that still isn't enough,
point Node at the CA explicitly: $env:NODE_EXTRA_CA_CERTS = 'C:\path\to\ca.pem'.
Only as an absolute last resort on a trusted network, -InsecureTLS disables
verification entirely (NOT recommended — the binaries get packed into a .exe you
redistribute).
#>
param([switch]$KeepLocales, [switch]$InsecureTLS)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$base = Join-Path $root 'out\afterterm-win32-x64'
$sfx  = Join-Path $root 'out\afterterm-setup.exe'
$7z   = 'C:\Program Files\7-Zip\7z.exe'
$sfxModule = 'C:\Program Files\7-Zip\7z.sfx'

# Guard: refuse only if afterterm is actually running FROM the folder this build
# overwrites. Building from a separate copy/worktree (whose out\ is a different
# path) is fine even while afterterm runs — that's the point of a build copy.
$runningHere = @(Get-Process afterterm -ErrorAction SilentlyContinue |
    Where-Object { $_.Path -and $_.Path.StartsWith($base, [StringComparison]::OrdinalIgnoreCase) })
if ($runningHere.Count -gt 0) {
    Write-Error "afterterm is running from '$base' (the folder this build overwrites). Close it, or run this from a separate copy/worktree whose out\ is elsewhere."
    exit 1
}
if (-not (Test-Path $7z) -or -not (Test-Path $sfxModule)) {
    Write-Error "7-Zip not found at '$7z'. Install with: winget install --id 7zip.7zip -e --source winget"
    exit 1
}

# ── Step 1: build the portable folder ────────────────────────────────────────
Write-Host "`n[1/3] Building portable app (this takes a few minutes)..." -ForegroundColor Cyan
Push-Location $root
# Make Node trust the OS (Windows) certificate store. On machines behind an
# intercepting proxy / corporate root CA, the Electron download otherwise fails
# with "unable to verify the first certificate". This is the SECURE fix — it
# uses the real installed CAs, not a bypass. (Node 22+/24.)
$env:NODE_OPTIONS = (("$env:NODE_OPTIONS --use-system-ca").Trim())
if ($InsecureTLS) {
    Write-Warning "TLS verification DISABLED (-InsecureTLS): downloaded Electron/native binaries are NOT authenticated and will be packed into a redistributable .exe. Only safe on a trusted network — prefer fixing the CA so --use-system-ca works."
    $env:NODE_TLS_REJECT_UNAUTHORIZED = '0'
}
npm run build
Pop-Location
if (-not (Test-Path "$base\afterterm.exe")) {
    Write-Error "Build did not produce $base\afterterm.exe"
    exit 1
}

# ── Step 2: prune dead weight (all regenerated by the next build) ─────────────
Write-Host "`n[2/3] Pruning dead weight..." -ForegroundColor Cyan
# (a) debug symbols — never loaded at runtime
Get-ChildItem $base -Recurse -Include *.pdb -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
# (b) wrong-arch node-pty prebuilds — this is an x64 build
$arm = "$base\resources\app\node_modules\node-pty\prebuilds\win32-arm64"
if (Test-Path $arm) { Remove-Item $arm -Recurse -Force }
# (c) non-English Electron locales — optional (skip with -KeepLocales for non-English Windows)
if (-not $KeepLocales) {
    Get-ChildItem "$base\locales" -File -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -ne 'en-US.pak' } | Remove-Item -Force -ErrorAction SilentlyContinue
}

# ── Step 3: pack into a self-extracting .exe ─────────────────────────────────
Write-Host "`n[3/3] Packing self-extracting installer (LZMA2 ultra)..." -ForegroundColor Cyan
if (Test-Path $sfx) { Remove-Item $sfx -Force }
& $7z a "-sfx$sfxModule" -t7z -m0=lzma2 -mx=9 -md=64m -mfb=64 -ms=on "$sfx" "$base" | Out-Null

if (Test-Path $sfx) {
    $mb = [math]::Round((Get-Item $sfx).Length / 1MB, 1)
    Write-Host "`nDONE → $sfx  ($mb MB)" -ForegroundColor Green
    Write-Host "Copy that one file to the other machine and double-click it to install." -ForegroundColor Green
} else {
    Write-Error "SFX packing failed — $sfx was not produced."
    exit 1
}
